version: "3.3"

services:
  turtle:
    image: dirobots/turtle:v1
    container_name: turtle
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - TERM=xterm-256color
      - QT_X11_NO_MITSHM=1
    volumes:
      - $XAUTH_PATH:$XAUTH_PATH
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/snd
      - /dev/bus/usb
      - /dev/video0
      - /dev/dri
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
